# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/caesar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import os 
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "../platforms"

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelTitle = QtWidgets.QLabel(self.centralwidget)
        self.labelTitle.setGeometry(QtCore.QRect(270, 20, 311, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.labelTitle.setFont(font)
        self.labelTitle.setObjectName("labelTitle")
        self.labelPlain = QtWidgets.QLabel(self.centralwidget)
        self.labelPlain.setGeometry(QtCore.QRect(60, 120, 55, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelPlain.setFont(font)
        self.labelPlain.setObjectName("labelPlain")
        self.textEditPlain = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditPlain.setGeometry(QtCore.QRect(180, 110, 581, 111))
        self.textEditPlain.setObjectName("textEditPlain")
        self.labelKey = QtWidgets.QLabel(self.centralwidget)
        self.labelKey.setGeometry(QtCore.QRect(60, 240, 55, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelKey.setFont(font)
        self.labelKey.setObjectName("labelKey")
        self.labelCipher = QtWidgets.QLabel(self.centralwidget)
        self.labelCipher.setGeometry(QtCore.QRect(60, 320, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelCipher.setFont(font)
        self.labelCipher.setObjectName("labelCipher")
        self.lineEditKey = QtWidgets.QTextEdit(self.centralwidget)
        self.lineEditKey.setGeometry(QtCore.QRect(180, 240, 591, 51))
        self.lineEditKey.setObjectName("lineEditKey")
        self.textEditCipher = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditCipher.setGeometry(QtCore.QRect(180, 320, 591, 101))
        self.textEditCipher.setObjectName("textEditCipher")
        self.btnEncrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btnEncrypt.setGeometry(QtCore.QRect(230, 450, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnEncrypt.setFont(font)
        self.btnEncrypt.setObjectName("btnEncrypt")
        self.btnDecrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btnDecrypt.setGeometry(QtCore.QRect(600, 450, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnDecrypt.setFont(font)
        self.btnDecrypt.setObjectName("btnDecrypt")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelTitle.setText(_translate("MainWindow", "CAESAR CIPHER"))
        self.labelPlain.setText(_translate("MainWindow", "Plain Text:    "))
        self.labelKey.setText(_translate("MainWindow", "Key:"))
        self.labelCipher.setText(_translate("MainWindow", "CipherText:"))
        self.btnEncrypt.setText(_translate("MainWindow", "Encypt"))
        self.btnDecrypt.setText(_translate("MainWindow", "Decrypt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
